package JFrames;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import timetable_app.Time;

/**
 *
 * @author Lenovo-x130
 */
public class LandingPage extends javax.swing.JFrame {

    // Gets the window's screen position
    int xx, xy;

    //Global variable for Hover Effect
    Color mouseEnterColor = new Color(255, 153, 0);
    Color mouseExitColor = new Color(51, 51, 51);

    DefaultTableModel model;

    /**
     * Creates new form landing_page
     */
    public LandingPage() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbl_menu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_close = new javax.swing.JLabel();
        txtTime = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1370, 770));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1370, 770));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/icons8_menu_48px_1.png"))); // NOI18N
        lbl_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_menuMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 50));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TIME-TABLE APPLICATION");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 510, -1));

        lbl_close.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lbl_close.setForeground(new java.awt.Color(255, 255, 255));
        lbl_close.setText("X");
        lbl_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_closeMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 10, 40, 40));

        txtTime.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txtTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 180, 30));

        txtDate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 190, 30));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 5, 50));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/male_user_50px.png"))); // NOI18N
        jLabel2.setText("Welcome, Admin");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 70));

        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 1370, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void init() {
        Time.setTime(txtTime, txtDate);  // Calling the setTime method from the Time class

        lowerPrimaryJtable();

        insertVerticalWords();

    }

    public void lowerPrimaryJtable() {
        // Create a table model with 6 rows and 13 columns

        model = new DefaultTableModel(5, 12);

        // Set column headers
        String[] columns = {"8:00-8:35", "8:35-9:10", "BREAK", "9:30-10:05", "10:05-10:40", "BREAK", "11:30-12:05", "12:05-12:40", "LUNCH", "2:00-2:35", "2:35-3:10", "3:10-3:45"};
        model.setColumnIdentifiers(columns);

        // Set row headers
        String[] rows = {"MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY"};

        // Create the table with the model
        JTable table = new JTable(model);
        table.setRowHeight(70);
        table.setGridColor(Color.BLACK);
// Make the table non-editable
        table.setDefaultEditor(Object.class, null);

        // Customize column header
// Set font style and color for column headers
        table.getTableHeader().setFont(new Font("Times New Roman", Font.BOLD, 18));
        table.getTableHeader().setForeground(new Color(0, 0, 139)); // Dark blue color

        // Create row header table
        DefaultTableModel rowHeaderModel = new DefaultTableModel();
        rowHeaderModel.setColumnIdentifiers(new String[]{"DAYS"});
        for (String row : rows) {
            rowHeaderModel.addRow(new Object[]{row});
        }

        // This creates a new JTable called rowHeaderTable, which will serve as the row headers
        JTable rowHeaderTable = new JTable(rowHeaderModel); //Creating the Row Header Table
        //Ensures that the row heights of rowHeaderTable (row headers) match those of table (main timetable)
        rowHeaderTable.setRowHeight(table.getRowHeight()); // Synchronizing Row Heights
        //This makes the rowHeaderTable non-editable, so users cannot modify the row headers.
        rowHeaderTable.setEnabled(false); // Disable editing on the Row Header Table

        // Set font style and color for row headers
        rowHeaderTable.setFont(new Font("Times New Roman", Font.BOLD, 16));
        rowHeaderTable.setForeground(Color.ORANGE.darker());

        table.getColumnModel().getColumn(0).setPreferredWidth(100); // Adjust width of first column

        //Setting the Preferred Size for the Row Header Table
        rowHeaderTable.setPreferredScrollableViewportSize(new Dimension(100, table.getPreferredSize().height));

        // Disable column reordering
        table.getTableHeader().setReorderingAllowed(false);

// Synchronize row heights
        for (int i = 0; i < table.getRowCount(); i++) {
            rowHeaderTable.setRowHeight(i, table.getRowHeight(i));
        }

        // Add the table to a scroll pane
        JScrollPane scrollPane = new JScrollPane(table);
        scrollPane.setRowHeaderView(rowHeaderTable);

        // Add the scroll pane to jPanel1
        jPanel1.add(scrollPane, BorderLayout.CENTER);

        // Refresh the panel to display the table
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    public void insertVerticalWords() {
//        // Insert 'BREAK' at the intersection of rows (row index 0-4) and BREAK (column index 2)
//        model.setValueAt("B", 0, 2);
//        model.setValueAt("R", 1, 2);
//        model.setValueAt("E", 2, 2);
//        model.setValueAt("A", 3, 2);
//        model.setValueAt("K", 4, 2);
//// Insert 'BREAK' at the intersection of rows (row index 0-4) and BREAK (column index 5)
//        model.setValueAt("B", 0, 5);
//        model.setValueAt("R", 1, 5);
//        model.setValueAt("E", 2, 5);
//        model.setValueAt("A", 3, 5);
//        model.setValueAt("K", 4, 5);
//// Insert 'LUNCH' at the intersection of rows (row index 0-4) and LUNCH (column index 8)
//        model.setValueAt("L", 0, 8);
//        model.setValueAt("U", 1, 8);
//        model.setValueAt("N", 2, 8);
//        model.setValueAt("C", 3, 8);
//        model.setValueAt("H", 4, 8);

// Words to insert and their respective column indices
    String[] words = {"BREAK", "BREAK", "LUNCH"};
    int[] columns = {2, 5, 8}; // Corresponding columns

    for (int i = 0; i < words.length; i++) {
        for (int j = 0; j < words[i].length(); j++) {
            model.setValueAt(String.valueOf(words[i].charAt(j)), j, columns[i]);
        }
    }

    }

    private void lbl_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closeMouseClicked
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to Close Application?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
//            dispose();
        }
    }//GEN-LAST:event_lbl_closeMouseClicked

    private void lbl_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_menuMouseClicked

//        if (panel_menu.isVisible()) {
//            panel_menu.setVisible(false);
//            // Adjust panel_display when panel_menu disappears
//            panel_display.setBounds(0, 0, parentPanel.getWidth(), parentPanel.getHeight());
//
//        } else {
//            panel_menu.setVisible(true);
//            // Adjust panel_display when panel_menu reappears
//            panel_display.setBounds(panel_menu.getWidth(), 0, parentPanel.getWidth() - panel_menu.getWidth(), 700);
//
//        }
//        // Force panel_display to re-layout its components
//        parentPanel.repaint();
    }//GEN-LAST:event_lbl_menuMouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked

        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LandingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_close;
    private javax.swing.JLabel lbl_menu;
    private javax.swing.JLabel txtDate;
    private javax.swing.JLabel txtTime;
    // End of variables declaration//GEN-END:variables
}
